// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD84ZDHn5XP6_g3jj4v08F697dGnU4vIkA',
    appId: '1:248222019875:web:6f00316029184c3f061c96',
    messagingSenderId: '248222019875',
    projectId: 'my-chat-app-gsg',
    authDomain: 'my-chat-app-gsg.firebaseapp.com',
    storageBucket: 'my-chat-app-gsg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT7w1c19GgOLFuq0OOVX6wio9pmtSvJm4',
    appId: '1:248222019875:android:c2c73164afaf5add061c96',
    messagingSenderId: '248222019875',
    projectId: 'my-chat-app-gsg',
    storageBucket: 'my-chat-app-gsg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDASJHi_Z0xrJwcIhM1CBOpZAB3UEf0HOo',
    appId: '1:248222019875:ios:a478363b0692b618061c96',
    messagingSenderId: '248222019875',
    projectId: 'my-chat-app-gsg',
    storageBucket: 'my-chat-app-gsg.appspot.com',
    iosClientId: '248222019875-72e6d7pd8sibpsqcfll75in9thj0up67.apps.googleusercontent.com',
    iosBundleId: 'com.oalshokri.chatAppClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDASJHi_Z0xrJwcIhM1CBOpZAB3UEf0HOo',
    appId: '1:248222019875:ios:a478363b0692b618061c96',
    messagingSenderId: '248222019875',
    projectId: 'my-chat-app-gsg',
    storageBucket: 'my-chat-app-gsg.appspot.com',
    iosClientId: '248222019875-72e6d7pd8sibpsqcfll75in9thj0up67.apps.googleusercontent.com',
    iosBundleId: 'com.oalshokri.chatAppClass',
  );
}
